"""Executive Brief — one-page markdown a CIO can take to the board."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy.orm import Session

from ..models.models import Aircraft, AgentRecommendation, SupplierIntelSignal
from .impact_engine import rank_operational_risks


def generate_executive_brief(db: Session, horizon_days: int = 90) -> str:
    now = datetime.utcnow()

    # Fleet
    total = db.query(Aircraft).count()
    fmc = db.query(Aircraft).filter(Aircraft.mission_status == "FMC").count()
    nmc = db.query(Aircraft).filter(Aircraft.mission_status == "NMC").count()
    at_risk = db.query(Aircraft).filter(Aircraft.mission_status == "AT_RISK").count()
    readiness = (fmc / total * 100) if total else 0

    # Intel
    active_intel = db.query(SupplierIntelSignal).filter(SupplierIntelSignal.is_active == True).count()  # noqa: E712
    crit_intel = db.query(SupplierIntelSignal).filter(
        SupplierIntelSignal.is_active == True,                                                          # noqa: E712
        SupplierIntelSignal.severity == "CRITICAL",
    ).count()

    # Recommendations
    open_critical = db.query(AgentRecommendation).filter(
        AgentRecommendation.status == "OPEN",
        AgentRecommendation.priority == "CRITICAL",
    ).count()
    open_high = db.query(AgentRecommendation).filter(
        AgentRecommendation.status == "OPEN",
        AgentRecommendation.priority == "HIGH",
    ).count()

    # Operational impact
    top_risks = rank_operational_risks(db, horizon_days=horizon_days, top_n=3)
    total_exposure = sum(r["dollar_exposure_usd"] for r in top_risks)

    posture = (
        "DEGRADED" if (nmc + at_risk) > 2 or crit_intel > 0 or open_critical > 0
        else "CAUTION" if (nmc + at_risk) > 0 or open_high > 0
        else "NOMINAL"
    )

    md = [
        f"# AeroRisk Executive Brief",
        f"*Generated {now.strftime('%Y-%m-%d %H:%M UTC')} · {horizon_days}-day horizon*",
        "",
        f"## Posture: **{posture}**",
        "",
        f"- Fleet readiness: **{readiness:.0f}%** ({fmc}/{total} FMC, {nmc} NMC, {at_risk} AT_RISK)",
        f"- Active external intel signals: **{active_intel}** ({crit_intel} CRITICAL)",
        f"- Open critical/high recommendations: **{open_critical} + {open_high}**",
        f"- Aggregate exposure across top 3 supplier-failure scenarios: **${total_exposure/1_000_000:.1f}M**",
        "",
        f"## Top operational risks",
        "",
    ]

    if not top_risks:
        md.append("_No supplier-failure scenarios produce material operational impact in this horizon._")
    for i, r in enumerate(top_risks, 1):
        platforms = ", ".join(f"{c} {p}" for p, c in sorted(r["platforms"].items(), key=lambda x: -x[1])[:3]) or "—"
        md += [
            f"### {i}. {r['supplier_name']} — {r['severity']}",
            f"- {r['one_liner']}",
            f"- Aircraft affected: **{r['aircraft_affected']}** ({platforms})",
            f"- Production delay: **{r['production_delay_days']} days**",
            f"- Dollar exposure: **${r['dollar_exposure_usd']/1_000_000:.2f}M** "
            f"(confidence {r['confidence']*100:.0f}%)",
            f"- Recommended alternate: **{r['top_alternate'] or 'NONE APPROVED'}**",
            "",
        ]

    md += [
        f"## Recommended decisions for this week",
        "",
        f"1. Approve qualification spend for the top alternate listed against the #1 risk.",
        f"2. Resolve the {open_critical} open CRITICAL recommendation(s) — see AI Recommendations page.",
        f"3. Pre-position safety stock against the highest-exposure single-source parts.",
        f"4. Brief PEO / program office with this impact report and the underlying drill-downs.",
        "",
        f"---",
        f"*Generated by AeroRisk AI. Every number is reconstructible from the underlying data model — no model hallucination.*",
    ]
    return "\n".join(md)
